ALTER TABLE item_list
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE member
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE item
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
